language: android
sudo: required
jdk: oraclejdk8

branches:
  only:
    - master
    - dev

before_cache:

 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:

 directories:

 - $HOME/.gradle/caches/

 - $HOME/.gradle/wrapper/

## Large files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source:
#Android SDKs
#Debian packages
#JDK packages
#Compiled binaries
#Docker images
# -  /usr/local/android-sdk/

env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

#     # Additional components
#     - extra-google-google_play_services
#     - extra-google-m2repository
#     - extra-android-m2repository
#     - addon-google_apis-google-26

#     # Specify at least one system image,
#     # if you need to run emulator(s) during your tests
# #    - sys-img-armeabi-v7a-android-26
# #    - sys-img-armeabi-v7a-android-19


#  https://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied/33820642
before_install:
 - chmod +x gradlew

install:
    - pushd $ANDROID_HOME
    - rm -rf tools
    - wget -q https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip -O tools.zip
    - unzip -q tools.zip
    - popd
    - touch $HOME/.android/repositories.cfg
    - yes | sdkmanager
        "build-tools;27.0.3"
        ndk-bundle
        "platforms;android-27" >/dev/null 

script:
- "./gradlew clean build --stacktrace --daemon"